Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - config/environments/development.rb

Layout/LineLength:
  Exclude: 
    - config/initializers/devise.rb

AllCops:
  SuggestExtensions: false
  Exclude:
    - bin/bundle
    - db/schema.rb
    - db/migrate/*